apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-logs
          emptyDir: {}
      containers:
        - name: log-output-writer
          image: haalto/log-output-writer
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/files
        - name: log-output-reader
          image: haalto/log-output-reader
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/files
