apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-application
  template:
    metadata:
      labels:
        app: ping-pong-application
    spec:
      volumes:
        - name: shared-logs
          persistentVolumeClaim:
            claimName: logs-claim
      containers:
        - name: ping-pong-application
          image: haalto/ping-pong-application
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/files
